config/routes.rb
Rails.application.routes.draw do
  
  resources :events do
    resources :expenses, controller: 'events/expenses'
    resources :revenues, controller: 'events/revenues'
  end
  
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  root to: 'events#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :revenues, dependent: :destroy
  has_many :expenses, dependent: :destroy
  
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :event
  
  def self.persisted
    where.not(id: nil)
  end
end

app/models/revenue.rb
class Revenue < ApplicationRecord
  belongs_to :event
  
  def self.persisted
    where.not(id: nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events/expenses_controller.rb
class Events::ExpensesController < ApplicationController
  #before_action :set_event
  #before_action :set_expense, only: [:edit, :update, :destroy]

  

  # POST /expenses
  # POST /expenses.json
  def create
    @event = Event.find(params[:event_id])
    @expense = @event.expenses.new(expense_params)
   
    if @expense.save
      flash[:success] = "Expense has been added."
    else
      flash.now[:danger] = "Error occured while adding expense."
    end
    redirect_to event_path(@event.id)
  end
  
  def edit
    @event = Event.find(params[:event_id])
    @expense = @event.expenses.find(params[:id])
  end

  
  def update
    @event = Event.find(params[:event_id])
    @expense = @event.expenses.find(params[:id])
    
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @event, notice: 'expense was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  
  
  
  def destroy
    @event = Event.find(params[:event_id])
    @expense = @event.expenses.find(params[:id])
    title = @expense.source
    
    @expense.destroy
    
    respond_to do |format|
      format.html { redirect_to event_path(@event.id), notice: "\"#{title}\" expense was successfully removed from #{@event.name.capitalize}." }
    end
    
  end

  private
    
    def set_event
      @event = Event.find(params[:event_id])
    end
   
    def set_expense
      @expense = @event.expenses.find(params[:id])
    end

    def expense_params
      params.require(:expense).permit(:source, :amount, :event_id)
    end
    
    
end

app/controllers/events/revenues_controller.rb
class Events::RevenuesController < ApplicationController
  #before_action :set_event
  #before_action :set_revenue, only: [:edit, :update, :destroy]


  def create
    @event = Event.find(params[:event_id])
    @revenue = @event.revenues.new(revenue_params)
   
    if @revenue.save
      flash[:success] = "Revenue has been added."
    else
      flash.now[:danger] = "Error occured while adding revenue."
    end
    redirect_to event_path(@event.id)
  end
  
  def edit
    @event = Event.find(params[:event_id])
    @revenue = @event.revenues.find(params[:id]) 
  end

  def update
    @event = Event.find(params[:event_id])
    @revenue = @event.revenues.find(params[:id])
    title = @revenue.source
    
    respond_to do |format|
      if @revenue.update(revenue_params)
        format.html { redirect_to @event, notice: "\"#{title}\" revenue was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end
  
  
  def destroy
    @event = Event.find(params[:event_id])
    @revenue = @event.revenues.find(params[:id])
    title = @revenue.source
    
    @revenue.destroy
    
    respond_to do |format|
      format.html { redirect_to event_path(@event.id), notice: "\"#{title}\" revenue was successfully removed from #{@event.name.capitalize}." }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:event_id])
    end
   
    def set_revenue
      @revenue = @event.revenues.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revenue_params
      params.require(:revenue).permit(:source, :amount, :event_id)
    end
    
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @revenue = @event.revenues.build
    @expense = @event.expenses.build
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :promoter, :paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_select :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :promoter %>
    <%= f.text_field :promoter, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :paid %>
    <%= f.check_box :paid %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/expenses/_expense.html.erb
<table class="table">
  
  <thead>
    <tr>
      <th>Source</th>
      <th>Amount</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>
  
  <tbody>
    <% @expense_running_total = 0 %>
    <% if @event.expenses.any? %>
      <% @event.expenses.persisted.each do |expense| %>
      <tr>
        <td><%= expense.source %></td>
        <td><%= number_to_currency(expense.amount) %></td>
        <td><%= link_to "Edit Expense", edit_event_expense_path(@event, expense), 
                    class: 'btn btn-sm btn-success' %></td>
        <td><%= link_to "Remove Expense", [@event, expense], 
                    method: :delete, 
                    class: 'btn btn-danger btn-sm',
                    data: {confirm: 'Are you sure?'} %></td>
                    
      </tr>
      <% @expense_running_total = @expense_running_total + expense.amount %>
      <% end %>
    <% end %>
  </tbody>
  
</table>

<br>

<h4>Expense Total: <%= number_to_currency(@expense_running_total) %></h4>

app/views/events/expenses/_form.html.erb
<%= form_for [@event, @expense] do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :source %>
    <%= f.text_field :source, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', @event %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Promoter</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event.id) %></td>
        <td><%= event.date %></td>
        <td><%= event.promoter %></td>
        <td><%= event.paid %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/revenues/_form.html.erb
<%= form_for [@event, @revenue] do |f| %>
  <% if @revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(revenue.errors.count, "error") %> prohibited this revenue from being saved:</h2>

      <ul>
      <% revenue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :source %>
    <%= f.text_field :source, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/revenues/_revenue.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Source</th>
      <th>Amount</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>

  <tbody>
    <% @revenue_running_total = 0 %>
    <% if @event.revenues.any? %>
      <% @event.revenues.persisted.each do |revenue| %>
        <tr>
          <td><%= revenue.source %></td>
          <td><%= number_to_currency(revenue.amount) %></td>
          <td><%= link_to "Edit Revenue", edit_event_revenue_path(@event, revenue),
                    class: 'btn btn-sm btn-success' %></td>
          <td><%= link_to "Remove Revenue", [@event, revenue], 
                    method: :delete, 
                    class: "btn btn-sm btn-danger",
                    data: { confirm: 'Are you sure?' } %></td>
          <% @revenue_running_total = @revenue_running_total + revenue.amount %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<h4>Revenue Total: <%= number_to_currency(@revenue_running_total) %></h4>

app/views/events/revenues/edit.html.erb
<h1>Editing Revenue</h1>

<%= render 'form' %>

<%= link_to 'Back', @event %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Promoter:</strong>
  <%= @event.promoter %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @event.paid %>
</p>

<br><br>

<h3>Revenues</h3>
<%= render 'events/revenues/revenue' %>

<br><br>

<h3>Expenses</h3>
<%= render 'events/expenses/expense' %>

<br>
<hr>

<% if (@revenue_running_total - @expense_running_total) >= 0 %>
  <h4>Net Profit: <%= number_to_currency(@revenue_running_total - @expense_running_total) %></h4>
<% else %>
  <h4>Net Loss: <span class="net-loss"><%= number_to_currency(@revenue_running_total - @expense_running_total) %></span></h4>
<% end %>
<hr>
<br>

<h4>Add Revenue</h4>
<%= render 'events/revenues/form' %>

<br>

<h4>Add Expense</h4>
<%= render 'events/expenses/form' %>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BizManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>